`define TINST_TYPE_WIDTH 		2
`define ADDR_WIDTH 				64
`define TMMA_PRECISION_WIDTH 	3
`define SARRAY_LOAD_WIDTH 		2048
`define SARRAY_STORE_WIDTH 		2048
`define TMMA_CNT_WIDTH          6

`define TINST_TYPE_TMMA 		0
`define TINST_TYPE_PRELOADC 	1
`define TINST_TYPE_POSTSTOREC 	2
`define TINST_TYPE_PRELOADA 	3